version: '3'
services:
  web:
    # 容器名
    container_name: yh-cloud-ui
    # 重启策略: 容器退出时总是重启容器
    restart: always
    # 构建镜像名称，没有build属性默认从远程仓库获取
    image: yh-cloud-ui
    # 指定设定上下文根目录，然后以该目录为准指定Dockerfile
    build:
      context: ./
      dockerfile: docker/Dockerfile-2
    environment:
      TZ: Asia/Shanghai
    ports:
      - 8900:8700
